// ---------------------------------------------------------------
// Whiteboard Interview — Static Question Bank
// 5 topics x 3 difficulties x 15 questions each = 225 questions.
// No API, no server, no key needed — script.js reads straight from this.
// ---------------------------------------------------------------

const QUESTION_BANK = {
  DSA: {
    Easy: [
      { question: "What is the difference between an array and a linked list?", hint: "Think contiguous memory vs. scattered nodes with pointers." },
      { question: "Explain how a stack differs from a queue.", hint: "LIFO vs. FIFO order of access." },
      { question: "What is the time complexity of binary search on a sorted array?", hint: "The array halves each comparison." },
      { question: "How do you reverse a string using a stack?", hint: "Push every character, then pop them all." },
      { question: "What is a hash table and how does it achieve near O(1) lookups?", hint: "Think about hashing keys to array indices." },
      { question: "Explain the difference between BFS and DFS traversal.", hint: "One uses a queue, the other a stack or recursion." },
      { question: "What is a linked list cycle, and how would you detect one?", hint: "Consider two pointers moving at different speeds." },
      { question: "How does bubble sort work, and what is its worst-case complexity?", hint: "Repeated adjacent swaps until sorted." },
      { question: "What is the difference between a binary tree and a binary search tree?", hint: "Ordering constraint on left and right children." },
      { question: "Explain what recursion is and give a simple example.", hint: "A function that calls itself with a base case." },
      { question: "What is the difference between linear search and binary search?", hint: "One needs a sorted input, the other doesn't." },
      { question: "How do you find the middle element of a linked list in one pass?", hint: "Use a slow and a fast pointer." },
      { question: "What is a palindrome, and how would you check if a string is one?", hint: "Compare characters from both ends inward." },
      { question: "Explain the difference between a min-heap and a max-heap.", hint: "Which element sits at the root differs." },
      { question: "What is the space complexity of an algorithm, and why does it matter?", hint: "Extra memory used relative to input size." }
    ],
    Medium: [
      { question: "How would you detect and remove a cycle in a linked list?", hint: "Floyd's cycle detection, then relink the tail." },
      { question: "Explain how quicksort partitions an array and its average time complexity.", hint: "Pivot selection drives the partitioning step." },
      { question: "How do you find the kth largest element in an unsorted array?", hint: "A heap or quickselect avoids full sorting." },
      { question: "What is dynamic programming, and how does it differ from plain recursion?", hint: "Overlapping subproblems get cached results." },
      { question: "How would you implement an LRU cache?", hint: "Combine a hash map with a doubly linked list." },
      { question: "Explain how a trie works and where it's useful.", hint: "Shared prefixes are stored once per path." },
      { question: "How do you find the lowest common ancestor in a binary tree?", hint: "Recurse down both subtrees and compare returns." },
      { question: "What is topological sorting, and when is it used?", hint: "Ordering nodes so dependencies come first." },
      { question: "How would you merge two sorted linked lists?", hint: "Compare heads and relink pointers iteratively." },
      { question: "Explain the sliding window technique with an example problem.", hint: "Expand and shrink a window over the array." },
      { question: "How do you check if a binary tree is height-balanced?", hint: "Compare left and right subtree heights recursively." },
      { question: "What is the difference between Dijkstra's and Bellman-Ford algorithms?", hint: "One handles negative edge weights, one doesn't." },
      { question: "How would you find all pairs in an array that sum to a target value?", hint: "A hash set can track complements seen so far." },
      { question: "Explain how a union-find (disjoint set) data structure works.", hint: "Path compression and union by rank speed it up." },
      { question: "How do you serialize and deserialize a binary tree?", hint: "Preorder traversal with markers for null nodes." }
    ],
    Hard: [
      { question: "How would you design an algorithm to find the median of two sorted arrays in logarithmic time?", hint: "Binary search on the smaller array's partition." },
      { question: "Explain how to solve the N-Queens problem using backtracking.", hint: "Place queens row by row, backtrack on conflict." },
      { question: "How would you find the longest increasing subsequence in an array?", hint: "Patience sorting gives an O(n log n) approach." },
      { question: "Explain how the KMP string matching algorithm avoids redundant comparisons.", hint: "A prefix table skips re-checking matched characters." },
      { question: "How would you design a data structure supporting insert, delete, and getRandom in O(1)?", hint: "Combine an array with a hash map of indices." },
      { question: "How do you find the shortest path in a graph with negative edge weights?", hint: "Bellman-Ford handles negatives; Dijkstra doesn't." },
      { question: "Explain how to solve the traveling salesman problem and its complexity.", hint: "Exact solutions are exponential; DP with bitmasking helps." },
      { question: "How would you find the maximum flow in a flow network?", hint: "Ford-Fulkerson augments paths until none remain." },
      { question: "Explain how segment trees support range queries and updates efficiently.", hint: "Each node represents a range, built recursively." },
      { question: "How do you solve the word ladder problem using BFS?", hint: "Treat each word as a node, one-letter edits as edges." },
      { question: "How would you detect if a directed graph has a cycle using topological sort?", hint: "Kahn's algorithm fails to process all nodes if a cycle exists." },
      { question: "Explain how suffix arrays are built and what they're used for.", hint: "Sorted suffixes enable fast substring search." },
      { question: "How would you design an autocomplete system with ranked suggestions?", hint: "A trie augmented with frequency counts at each node." },
      { question: "How do you solve the longest common subsequence problem, and what's its complexity?", hint: "A 2D DP table over both string lengths." },
      { question: "Explain how skip lists achieve logarithmic search time without balancing.", hint: "Randomized multi-level linked lists act as shortcuts." }
    ]
  },
  DBMS: {
    Easy: [
      { question: "What is the difference between DBMS and RDBMS?", hint: "Relational structure and constraints set RDBMS apart." },
      { question: "Explain what a primary key is and why it must be unique.", hint: "It uniquely identifies each row in a table." },
      { question: "What is a foreign key, and what purpose does it serve?", hint: "It links a row to a primary key in another table." },
      { question: "What is normalization, and why is it used?", hint: "Reducing redundancy by organizing data into related tables." },
      { question: "Explain the difference between DELETE and TRUNCATE.", hint: "One is row-by-row and logged, the other resets the table." },
      { question: "What is a JOIN in SQL, and name two common types.", hint: "Combining rows from two or more tables." },
      { question: "What is the difference between a clustered and non-clustered index?", hint: "One physically reorders the table's data." },
      { question: "Explain what ACID properties mean in a database.", hint: "Atomicity, Consistency, Isolation, Durability." },
      { question: "What is the difference between UNION and UNION ALL?", hint: "One removes duplicate rows, the other keeps them." },
      { question: "What is a view in SQL, and why would you use one?", hint: "A virtual table backed by a stored query." },
      { question: "Explain the difference between WHERE and HAVING clauses.", hint: "One filters rows, the other filters grouped results." },
      { question: "What is a composite key?", hint: "A primary key made of more than one column." },
      { question: "What does the GROUP BY clause do?", hint: "Aggregates rows sharing the same column values." },
      { question: "Explain the difference between SQL and NoSQL databases.", hint: "Schema rigidity and data model flexibility differ." },
      { question: "What is a constraint in SQL, and give two examples.", hint: "Rules enforced on column values, like NOT NULL." }
    ],
    Medium: [
      { question: "Explain the difference between 2NF and 3NF with an example.", hint: "Transitive dependency removal separates the two." },
      { question: "What is a deadlock in a database, and how can it be prevented?", hint: "Two transactions waiting on each other's locks." },
      { question: "Explain how indexing improves query performance and its trade-offs.", hint: "Faster reads at the cost of slower writes and storage." },
      { question: "What is the difference between OLTP and OLAP systems?", hint: "Transactional workloads versus analytical workloads." },
      { question: "Explain how a database transaction ensures isolation between concurrent users.", hint: "Isolation levels control what one transaction can see." },
      { question: "What is denormalization, and when would you use it?", hint: "Trading redundancy for read performance." },
      { question: "How does a B-tree index work, and why is it used in databases?", hint: "Balanced structure keeps lookup depth logarithmic." },
      { question: "Explain the difference between optimistic and pessimistic locking.", hint: "One assumes conflicts are rare, the other assumes they aren't." },
      { question: "What is a stored procedure, and what are its advantages?", hint: "Precompiled SQL logic stored on the server." },
      { question: "Explain how query execution plans help optimize SQL performance.", hint: "They show how the engine will fetch and join data." },
      { question: "What is the CAP theorem, and how does it apply to distributed databases?", hint: "You can only guarantee two of three properties at once." },
      { question: "Explain the difference between horizontal and vertical partitioning.", hint: "Splitting rows versus splitting columns across storage." },
      { question: "What is a materialized view, and how does it differ from a regular view?", hint: "One stores precomputed results physically." },
      { question: "Explain how replication works in a distributed database.", hint: "Copies of data are kept in sync across nodes." },
      { question: "What is the difference between a shared lock and an exclusive lock?", hint: "One allows concurrent reads, the other blocks all access." }
    ],
    Hard: [
      { question: "How would you design a database schema for a multi-tenant SaaS application?", hint: "Consider shared schema vs. schema-per-tenant trade-offs." },
      { question: "Explain how MVCC (multi-version concurrency control) avoids read locks.", hint: "Readers see a consistent snapshot instead of blocking writers." },
      { question: "How would you optimize a slow query joining multiple large tables?", hint: "Check indexes, join order, and the execution plan." },
      { question: "Explain how database sharding works and its challenges.", hint: "Splitting data across nodes by a shard key." },
      { question: "How does a write-ahead log ensure durability after a crash?", hint: "Changes are logged before being applied to data files." },
      { question: "Explain the trade-offs between strong and eventual consistency.", hint: "Latency and availability trade against immediate correctness." },
      { question: "How would you design an indexing strategy for a table with billions of rows?", hint: "Consider composite indexes and partitioning together." },
      { question: "Explain how distributed transactions use two-phase commit.", hint: "A prepare phase precedes a commit phase across nodes." },
      { question: "How would you handle schema migrations on a live production database with zero downtime?", hint: "Backward-compatible changes rolled out incrementally." },
      { question: "Explain how database connection pooling improves performance under load.", hint: "Reusing connections avoids repeated setup overhead." },
      { question: "How would you detect and resolve a live deadlock in a production system?", hint: "Monitor lock wait graphs and kill the victim transaction." },
      { question: "Explain how columnar storage differs from row storage and when to use each.", hint: "Analytics favor columns; transactions favor rows." },
      { question: "How would you design a system to handle eventual consistency conflicts in a distributed database?", hint: "Consider vector clocks or last-write-wins strategies." },
      { question: "Explain how query caching works and its invalidation challenges.", hint: "Stale cache entries after underlying data changes." },
      { question: "How would you design a database for high write throughput with minimal read latency?", hint: "Consider write-optimized storage engines and read replicas." }
    ]
  },
  OOP: {
    Easy: [
      { question: "What are the four pillars of object-oriented programming?", hint: "Encapsulation, abstraction, inheritance, polymorphism." },
      { question: "Explain the difference between a class and an object.", hint: "One is the blueprint, the other is the instance." },
      { question: "What is inheritance, and why is it useful?", hint: "Reusing behavior from a parent class." },
      { question: "What is encapsulation, and how is it implemented?", hint: "Bundling data with methods and restricting access." },
      { question: "Explain the difference between method overloading and overriding.", hint: "Same class vs. subclass redefinition." },
      { question: "What is polymorphism, with a simple example?", hint: "One interface, many implementations." },
      { question: "What is an abstract class, and how does it differ from an interface?", hint: "One can have partial implementation, the other typically can't." },
      { question: "Explain the difference between a constructor and a destructor.", hint: "One initializes an object, the other cleans it up." },
      { question: "What is the 'this' keyword used for in object-oriented languages?", hint: "It refers to the current object instance." },
      { question: "What is a static method, and how does it differ from an instance method?", hint: "It belongs to the class, not any single object." },
      { question: "Explain what access modifiers are and name a few common ones.", hint: "Public, private, protected control visibility." },
      { question: "What is composition, and how does it differ from inheritance?", hint: "Building objects from other objects rather than extending." },
      { question: "What does a 'has-a' relationship mean in OOP design?", hint: "One object contains another as a field." },
      { question: "Explain what a getter and setter method are used for.", hint: "Controlled access to an object's private fields." },
      { question: "What is the purpose of the 'super' keyword in inheritance?", hint: "It refers to the parent class's members." }
    ],
    Medium: [
      { question: "Explain the SOLID principles with a brief example of each.", hint: "Five guidelines for maintainable object-oriented design." },
      { question: "What is the difference between an abstract class and an interface, and when would you choose one over the other?", hint: "Shared state vs. pure contract." },
      { question: "Explain the Singleton design pattern and a potential downside of using it.", hint: "One instance, globally accessible — but hard to test." },
      { question: "What is the difference between composition and aggregation?", hint: "Ownership and lifecycle dependency differ." },
      { question: "Explain how the Factory design pattern decouples object creation from usage.", hint: "A separate method decides which class to instantiate." },
      { question: "What is method overriding's relationship to runtime polymorphism?", hint: "The actual object type decides which method runs." },
      { question: "Explain the Liskov Substitution Principle with an example violation.", hint: "Subtypes should be substitutable for their base type." },
      { question: "What is the Observer design pattern, and where is it commonly used?", hint: "Subscribers get notified when a subject's state changes." },
      { question: "Explain the difference between shallow copy and deep copy of an object.", hint: "One copies references, the other copies nested data too." },
      { question: "What is dependency injection, and why does it improve testability?", hint: "Dependencies are passed in rather than created internally." },
      { question: "Explain how interfaces support multiple inheritance in languages that don't allow it directly.", hint: "A class can implement several interfaces at once." },
      { question: "What is the Strategy design pattern, and how does it avoid conditional logic?", hint: "Swap behavior via interchangeable strategy objects." },
      { question: "Explain the difference between tight coupling and loose coupling.", hint: "How much one component depends on another's internals." },
      { question: "What is operator overloading, and what are its risks if overused?", hint: "Custom meaning for operators can hurt readability." },
      { question: "Explain how the Decorator pattern adds behavior without modifying existing code.", hint: "Wrapping objects to extend functionality dynamically." }
    ],
    Hard: [
      { question: "How would you design a plugin architecture using interfaces and dependency injection?", hint: "Define a contract, discover and register plugins at runtime." },
      { question: "Explain how the Visitor design pattern separates algorithms from object structures.", hint: "Operations live outside the classes they act on." },
      { question: "How would you refactor a god class that violates the Single Responsibility Principle?", hint: "Split responsibilities into smaller, focused classes." },
      { question: "Explain how covariance and contravariance apply to method overriding in typed languages.", hint: "Return and parameter type flexibility in subclasses." },
      { question: "How would you design a class hierarchy that avoids the diamond problem?", hint: "Favor composition or interfaces over multiple inheritance." },
      { question: "Explain how the Command pattern enables undo/redo functionality.", hint: "Each action is encapsulated as a reversible object." },
      { question: "How would you design an extensible rules engine using OOP principles?", hint: "Represent rules as interchangeable, composable objects." },
      { question: "Explain the trade-offs between inheritance-heavy and composition-heavy architectures at scale.", hint: "Flexibility versus rigid, deep hierarchies." },
      { question: "How would you implement thread-safe lazy initialization of a Singleton?", hint: "Consider double-checked locking or a static holder class." },
      { question: "Explain how the Adapter and Facade patterns differ, with a use case for each.", hint: "One converts an interface, the other simplifies a subsystem." },
      { question: "How would you design a caching layer using the Proxy pattern?", hint: "A proxy intercepts calls to add caching transparently." },
      { question: "Explain how the Template Method pattern enforces an algorithm's structure while allowing customization.", hint: "A base class fixes the steps, subclasses fill in details." },
      { question: "How would you design a system of interchangeable payment gateways using the Strategy pattern?", hint: "Each gateway implements a common payment interface." },
      { question: "Explain the risks of deep inheritance chains and how to mitigate them.", hint: "Fragility and tight coupling grow with depth." },
      { question: "How would you apply the Open/Closed Principle when adding a new feature to an existing large codebase?", hint: "Extend behavior without modifying existing tested code." }
    ]
  },
  OS: {
    Easy: [
      { question: "What is the difference between a process and a thread?", hint: "Threads share memory within a process." },
      { question: "What is the purpose of an operating system?", hint: "It manages hardware resources for applications." },
      { question: "Explain what a deadlock is in operating systems.", hint: "Processes waiting forever on each other's resources." },
      { question: "What is virtual memory, and why is it used?", hint: "It lets programs use more memory than physically exists." },
      { question: "Explain the difference between multitasking and multithreading.", hint: "Multiple processes versus multiple threads within one." },
      { question: "What is a system call, and why is it needed?", hint: "It's how programs request kernel services." },
      { question: "Explain the difference between paging and segmentation.", hint: "Fixed-size blocks versus variable-size logical divisions." },
      { question: "What is a context switch?", hint: "Saving and restoring a process's execution state." },
      { question: "What is the difference between a kernel and a shell?", hint: "One is the core, the other is the user interface to it." },
      { question: "Explain what a semaphore is used for.", hint: "A counter that coordinates access to shared resources." },
      { question: "What is thrashing in the context of memory management?", hint: "Excessive paging that stalls actual progress." },
      { question: "Explain the difference between preemptive and non-preemptive scheduling.", hint: "Whether a running process can be interrupted." },
      { question: "What is a zombie process?", hint: "A finished process whose exit status hasn't been read." },
      { question: "Explain what caching does at the OS level and why it improves performance.", hint: "Frequently used data is kept closer to the CPU." },
      { question: "What is the difference between logical and physical addresses?", hint: "One is generated by the CPU, the other maps to real memory." }
    ],
    Medium: [
      { question: "Explain the four necessary conditions for a deadlock to occur.", hint: "Mutual exclusion, hold and wait, no preemption, circular wait." },
      { question: "What is the difference between a mutex and a semaphore?", hint: "Ownership of the lock is the key distinction." },
      { question: "Explain how the Banker's algorithm avoids deadlocks.", hint: "It only grants requests that keep the system in a safe state." },
      { question: "What is priority inversion, and how can it be resolved?", hint: "A low-priority task blocks a higher-priority one." },
      { question: "Explain how the round-robin scheduling algorithm works and its trade-offs.", hint: "Fixed time slices cycle through the ready queue." },
      { question: "What is the producer-consumer problem, and how is it solved with semaphores?", hint: "Coordinating a shared buffer between two processes." },
      { question: "Explain the difference between internal and external fragmentation.", hint: "Wasted space within a block versus between blocks." },
      { question: "What is a page fault, and what happens when one occurs?", hint: "A requested page isn't currently in memory." },
      { question: "Explain how the readers-writers problem is typically solved.", hint: "Multiple readers can share access, but writers need exclusivity." },
      { question: "What is the difference between a monolithic kernel and a microkernel?", hint: "How much runs in kernel space versus user space." },
      { question: "Explain how the Least Recently Used (LRU) page replacement algorithm works.", hint: "Evict the page that hasn't been touched the longest." },
      { question: "What is a race condition, and how do you prevent one?", hint: "Unsynchronized access to shared data causes it." },
      { question: "Explain the difference between spinlocks and blocking locks.", hint: "Busy-waiting versus yielding the CPU while waiting." },
      { question: "What is copy-on-write, and where is it used in operating systems?", hint: "Pages are only duplicated when modified, common in fork()." },
      { question: "Explain how demand paging improves memory efficiency.", hint: "Pages load only when actually accessed." }
    ],
    Hard: [
      { question: "How would you design a scheduler that balances fairness and low latency for interactive processes?", hint: "Consider multilevel feedback queues with dynamic priorities." },
      { question: "Explain how a distributed system achieves mutual exclusion without shared memory.", hint: "Consider token-passing or quorum-based algorithms." },
      { question: "How does the operating system handle a page fault storm under memory pressure?", hint: "Aggressive eviction can trigger thrashing if unmanaged." },
      { question: "Explain how real-time operating systems guarantee bounded response times.", hint: "Deterministic scheduling with worst-case execution time analysis." },
      { question: "How would you diagnose and fix a priority inversion issue in a production system?", hint: "Look for priority inheritance or ceiling protocols." },
      { question: "Explain how NUMA (non-uniform memory access) architecture affects OS scheduling decisions.", hint: "Memory locality to a CPU node affects placement choices." },
      { question: "How would you design a lock-free data structure for a multi-core system?", hint: "Consider atomic compare-and-swap operations." },
      { question: "Explain how the OS balances load across multiple CPU cores.", hint: "Consider work-stealing and core affinity strategies." },
      { question: "How would you design a memory allocator that minimizes fragmentation under heavy churn?", hint: "Consider size-class buckets like slab allocation." },
      { question: "Explain how journaling file systems recover from a crash without data corruption.", hint: "Changes are logged before being committed to disk." },
      { question: "How would you debug a kernel-level deadlock involving multiple resource types?", hint: "Trace the resource allocation graph for circular waits." },
      { question: "Explain how hypervisors isolate virtual machines at the OS level.", hint: "Each VM gets virtualized access to hardware resources." },
      { question: "How would you design an I/O scheduler for an SSD versus a spinning disk?", hint: "Seek time matters for one but not the other." },
      { question: "Explain how copy-on-write fork() improves process creation performance.", hint: "Memory pages are shared until either process writes." },
      { question: "How would you design a system to detect and recover from thrashing in real time?", hint: "Monitor page fault rate against CPU utilization." }
    ]
  },
  CN: {
    Easy: [
      { question: "What is the difference between the OSI model and the TCP/IP model?", hint: "Seven layers versus four, mapped conceptually." },
      { question: "Explain what an IP address is and its two common versions.", hint: "A numeric identifier for a device on a network." },
      { question: "What is the difference between TCP and UDP?", hint: "Reliable and ordered versus fast and connectionless." },
      { question: "What is a MAC address, and how does it differ from an IP address?", hint: "One is hardware-based, the other is logical." },
      { question: "Explain what DNS does and why it's needed.", hint: "It translates domain names into IP addresses." },
      { question: "What is the difference between a hub, a switch, and a router?", hint: "They operate at different layers of the network." },
      { question: "What is the purpose of the three-way handshake in TCP?", hint: "SYN, SYN-ACK, ACK establish a connection." },
      { question: "Explain what a subnet mask is used for.", hint: "It separates network bits from host bits." },
      { question: "What is the difference between HTTP and HTTPS?", hint: "One is encrypted using TLS, the other isn't." },
      { question: "What is a firewall, and what is its purpose?", hint: "It filters traffic based on defined rules." },
      { question: "Explain what a port number is and give an example of a well-known port.", hint: "It identifies a specific service on a host." },
      { question: "What is the difference between a LAN and a WAN?", hint: "Geographic scope is the main distinction." },
      { question: "What is DHCP, and what problem does it solve?", hint: "It automatically assigns IP addresses to devices." },
      { question: "Explain what latency and bandwidth mean in networking.", hint: "Delay versus data-carrying capacity." },
      { question: "What is the purpose of the ping command?", hint: "It tests reachability and measures round-trip time." }
    ],
    Medium: [
      { question: "Explain how TCP ensures reliable data delivery.", hint: "Sequence numbers, acknowledgments, and retransmission." },
      { question: "What is the difference between symmetric and asymmetric encryption in the context of HTTPS?", hint: "Key exchange uses one, bulk data uses the other." },
      { question: "Explain how ARP resolves an IP address to a MAC address.", hint: "A broadcast request asks 'who has this IP?'" },
      { question: "What is NAT, and why is it used in home networks?", hint: "It lets multiple devices share one public IP." },
      { question: "Explain the difference between distance-vector and link-state routing protocols.", hint: "What information each router shares with neighbors." },
      { question: "What is a VPN, and how does it secure network traffic?", hint: "An encrypted tunnel over a public network." },
      { question: "Explain how TCP's congestion control avoids overwhelming the network.", hint: "The sending window adjusts based on network feedback." },
      { question: "What is the difference between a stateful and a stateless firewall?", hint: "Whether connection context is tracked over time." },
      { question: "Explain how DNS resolution works, from browser request to IP address.", hint: "Recursive queries walk from root to authoritative servers." },
      { question: "What is a CDN, and how does it reduce latency for end users?", hint: "Content is cached closer to the requesting user." },
      { question: "Explain the difference between TCP's slow start and congestion avoidance phases.", hint: "Growth rate of the congestion window changes." },
      { question: "What is a subnet, and how does subnetting improve network efficiency?", hint: "Dividing a network reduces broadcast domain size." },
      { question: "Explain how SSL/TLS handshakes establish a secure connection.", hint: "Certificates and key exchange happen before data flows." },
      { question: "What is the difference between unicast, multicast, and broadcast?", hint: "How many recipients a message is sent to." },
      { question: "Explain how load balancers distribute traffic across servers.", hint: "Algorithms like round-robin or least-connections decide routing." }
    ],
    Hard: [
      { question: "How would you design a network architecture to minimize latency for a global real-time application?", hint: "Consider edge servers and anycast routing." },
      { question: "Explain how BGP determines routing paths between autonomous systems.", hint: "Path attributes and policy decide the best route." },
      { question: "How would you diagnose intermittent packet loss in a production network?", hint: "Check for congestion, faulty hardware, or MTU mismatches." },
      { question: "Explain how QUIC improves on TCP for modern web applications.", hint: "It reduces handshake overhead and avoids head-of-line blocking." },
      { question: "How would you design a system to detect and mitigate a DDoS attack in real time?", hint: "Rate limiting, traffic scrubbing, and anomaly detection." },
      { question: "Explain how software-defined networking (SDN) decouples the control and data planes.", hint: "A centralized controller manages forwarding decisions." },
      { question: "How would you design a multi-region failover strategy for a latency-sensitive service?", hint: "Health checks combined with DNS or anycast failover." },
      { question: "Explain how TCP handles out-of-order packet delivery and retransmission.", hint: "Sequence numbers let the receiver reorder and request gaps." },
      { question: "How would you troubleshoot a routing loop in a large enterprise network?", hint: "Check TTL decrements and routing table inconsistencies." },
      { question: "Explain how anycast routing is used to improve availability and performance.", hint: "The same IP is announced from multiple locations." },
      { question: "How would you design network segmentation to contain a security breach?", hint: "VLANs and firewalls limit lateral movement." },
      { question: "Explain how MPLS improves traffic engineering compared to standard IP routing.", hint: "Label-based forwarding avoids repeated route lookups." },
      { question: "How would you optimize a network for high-throughput, low-latency financial trading?", hint: "Consider kernel bypass and minimizing hop count." },
      { question: "Explain how consistent hashing helps distribute load in a distributed cache.", hint: "Minimal remapping occurs when nodes are added or removed." },
      { question: "How would you design a zero-trust network architecture for a large organization?", hint: "Verify every request regardless of network location." }
    ]
  }
};
